-- Create table MEDICINE_DISTRIBUTION
-- For all the example to work this should be created under C##USER1

CREATE TABLE MEDICINE_DISTRIBUTION 
(
  ID VARCHAR2(20) NOT NULL 
, PATIENT_ID VARCHAR2(20) NOT NULL 
, MEDICINE_ID VARCHAR2(20) NOT NULL 
, DISTRIBUTION_ID VARCHAR2(20) 
, COMMENTS VARCHAR2(2000) 
, CONSTRAINT MEDICINE_DISTRIBUTION_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
