-- Create table PATIENT_DETAILS
-- For all the example to work this should be created under C##USER1

CREATE TABLE PATIENT_DETAILS 
(
  ID VARCHAR2(20) NOT NULL 
, PATIENT_TITLE VARCHAR2(8) 
, PATIENT_FIRSTNAME VARCHAR2(50) NOT NULL 
, PATIENT_LASTNAME VARCHAR2(50) NOT NULL 
, PATIENT_GENDER VARCHAR2(1) 
, PATIENT_PHONEHOME VARCHAR2(20) 
, PATIENT_PHONEMOBILE VARCHAR2(20) 
, PATIENT_EMAIL VARCHAR2(50) 
, PATIENT_SSN VARCHAR2(20) 
, CONSTRAINT PATIENT_DETAILS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN PATIENT_DETAILS.PATIENT_EMAIL IS 'patient email account';
COMMENT ON COLUMN PATIENT_DETAILS.PATIENT_SSN IS 'Patient Social Security Number';
